@startuml
'---------------------------------------------------------------------
' 2020/06/25    吉冨    Rev0.1    新規作成

'---------------------------------------------------------------------

title kiwiテスト 論理図

!define MAIN_ENTITY #white
!define MASTER_COLOR yellow
!define TRANSACTION_COLOR afeeee
!define ENTITIY_COLOR e6e6fa


folder "運用" #ffffe0  {
    entity "テスト実行" <<T,MASTER_COLOR>> MAIN_ENTITY  {
        + テスト実行ID[PK]
        --
        概要
        テスト実行ビルド名
        管理者
        テスト担当者
        コメント
        --
        不具合
    }

    entity "不具合報告" <<T,MASTER_COLOR>> MAIN_ENTITY  {
        + 不具合報告ID[PK]
        --
        概要
        製品プロダクト
        バージョン
        テスト実行ビルド名
        テスト担当者
        --
        不具合の説明
        頻度
        再現手順
        エラーメッセージ
        期待される正常時の結果
        追加情報
    }
}

folder "テスト管理者にて作成" #ffffe0  {

    entity "テストプラン" <<T,MASTER_COLOR>> MAIN_ENTITY  {
        + テストプランID[PK]
        --
        テストプラン名
        開発プロダクト
        バージョン
        テストの種類
        --
        概要
    }

    entity "テストケース" <<T,MASTER_COLOR>> MAIN_ENTITY  {
        + テストケースID[PK]
        --
        テストケース名
        概要
        テスト担当者
        開発プロダクト
        カテゴリー
        コンポーネント
        優先度
        ステータス
        （承認待ち、確認済み、無効、更新が必要）
        作成者
        タグ
        テキスト
        --
        シナリオ
        条件
        手順
        期待される結果
    }
}


    テスト実行 ||-ri-|{ テストプラン
    テスト実行 ||-do-|{ 不具合報告
    テストプラン ||-ri-|{ テストケース


@enduml
