# Generated by Django 2.2.6 on 2019-11-10 10:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'アプリケーション',
                'verbose_name_plural': 'アプリケーション',
                'db_table': 'm_application',
            },
        ),
        migrations.CreateModel(
            name='M_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('base_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'db_table': 'm_company',
            },
        ),
        migrations.CreateModel(
            name='M_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '言語',
                'verbose_name_plural': '言語',
                'db_table': 'm_language',
            },
        ),
        migrations.CreateModel(
            name='M_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('header', models.CharField(max_length=50, unique=True)),
                ('footer', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
                'db_table': 'm_message',
            },
        ),
        migrations.CreateModel(
            name='M_RequestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestcategory_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '申請区分',
                'verbose_name_plural': '申請区分',
                'db_table': 'm_requestcategory',
            },
        ),
        migrations.CreateModel(
            name='T_License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, unique=True)),
                ('hid', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licenses.M_Application', verbose_name='アプリケーション名')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licenses.M_Company', verbose_name='会社')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licenses.M_Language', verbose_name='言語')),
            ],
            options={
                'verbose_name': 'ライセンス',
                'verbose_name_plural': 'ライセンス',
                'db_table': 't_license',
            },
        ),
        migrations.CreateModel(
            name='T_Publication',
            fields=[
                ('increment_num', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('grant_points', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_point', models.PositiveIntegerField(blank=True, null=True)),
                ('renewal_deadline_notification', models.DateField(blank=True, null=True)),
                ('renewal_application_accepted', models.DateField(blank=True, null=True)),
                ('renewal_application_send', models.DateField(blank=True, null=True)),
                ('renewal_key_publish_notification', models.DateField(blank=True, null=True)),
                ('discontinued_product_collection', models.DateField(blank=True, null=True)),
                ('memo', models.CharField(max_length=100)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='licenses.T_License')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ライセンス発行履歴',
                'verbose_name_plural': 'ライセンス発行履歴',
                'db_table': 't_publication',
            },
        ),
        migrations.CreateModel(
            name='T_Operation',
            fields=[
                ('increment_num', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starting_count', models.PositiveIntegerField(blank=True, null=True)),
                ('weekly_report_count', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_report_count', models.PositiveIntegerField(blank=True, null=True)),
                ('memo', models.CharField(max_length=100)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='licenses.T_License')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用履歴',
                'verbose_name_plural': '使用履歴',
                'db_table': 't_operation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('favorite_words', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='licenses.T_Publication')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
