# Generated by Django 2.2.5 on 2019-09-17 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseapp', '0002_company_company_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateField(default=datetime.datetime.now, verbose_name='登録日')),
                ('begin_date', models.DateField(default=datetime.datetime.now, verbose_name='開始日')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='終了日')),
                ('serial_no', models.CharField(max_length=128, verbose_name='シリアルNO')),
                ('price', models.IntegerField(help_text='単位は日本円', verbose_name='販売金額')),
                ('grant_point', models.IntegerField(default=0, verbose_name='付与ポイント')),
                ('remainingu_point', models.IntegerField(default=0, verbose_name='残ポイント')),
                ('comment', models.CharField(max_length=500, verbose_name='コメント')),
            ],
            options={
                'verbose_name': 'ライセンス詳細',
                'verbose_name_plural': 'ライセンス詳細',
                'db_table': 'license_detail',
            },
        ),
    ]
