@startuml ER図

'-------------------------------------------------
' 2019/09/17 吉冨 新規作成 
'
'-------------------------------------------------

!define MAIN_ENTITY #E2EFDA
!define MAIN_ENTITY_2 #FCE4D6

!define METAL #F2F2F2
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
}

package "ライセンス管理システム" as target_system {
    entity "ライセンス管理テーブル" as License <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + ライセンス管理ID [PK]
        --
        # ライセンス明細ID [FK]
        # ユーザーID [FK]
        # 会社ID [FK]
        # 言語ID [FK]
        # メッセージID [FK]
        # 使用履歴ID [FK]
        登録者
        登録日
        使用者
        責任者
        コメント
    }

    entity "ライセンス明細テーブル" as LicenseDetail <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + ライセンス明細ID [PK]
        --
        # ソフトID [FK]
        ソフト名
        更新日時
        開始日
        終了日
        登録者
        登録日
        シリアルNO
        販売金額
        付与ポイント
        残ポイント
        コメント
    }

    entity "ソフトマスタ" as Softwear <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + ソフトID [PK]
        --
        ソフト名
        コメント
    }

    note bottom of Softwear : ソフト名毎にライセンス更新されるため明細テーブルに入る


    entity "ユーザーマスタ" as User <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + ユーザーID [PK]
        --
        担当者名
        拠点名
        メールアドレス
        役職
        言語
        コメント
    }

    entity "会社マスタ" as Company <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + 会社ID [PK]
        --
        会社名
        コメント
    }

    entity "言語マスタ" as Language <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + 言語ID [PK]
        --
        言語名
        コメント
    }

    entity "メッセージマスタ" as Message <<M,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + メッセージID [PK]
        --
        本文
        ヘッダー
        フッター
        コメント
    }

    entity "メッセージ履歴" as MessageHistory <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + メッセージ履歴ID [PK]
        --
        # メッセージID[FK]
        登録日
    }

    entity "使用履歴" as UseHistory <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + 使用履歴ID [PK]
        --
        # メッセージID[FK]
       使用回数
       1回目起動日
       10回目起動日
       100回目起動日
       1000回目起動日
       最終起動日
       登録者
       登録日
       コメント
    }

}

License        ||--|{     LicenseDetail
License         }-up-||   User
License         }--||     MessageHistory
License         }-up-||   Company
License         }-up-||   Language
License        ||-{       UseHistory   

LicenseDetail   }-||      Softwear
MessageHistory ||-{       Message

'note bottom of customer : 別プロジェクト\nDB-Linkで参照する

@enduml