# Generated by Django 2.2.5 on 2019-09-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenseapp', '0005_auto_20190917_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='memo',
        ),
        migrations.AddField(
            model_name='license',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='licensedetail',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='software',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='コメント'),
        ),
    ]
