# Generated by Django 2.0.4 on 2019-09-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
    ]
