# Generated by Django 2.2.5 on 2019-09-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_auto_20190915_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'license',
            },
        ),
        migrations.AddField(
            model_name='kakeibo',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kakeibo.License', verbose_name='ライセンス名'),
            preserve_default=False,
        ),
    ]
