# Generated by Django 2.2.5 on 2019-09-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_auto_20190915_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'ライセンス', 'verbose_name_plural': 'ライセンス'},
        ),
    ]
