@startuml

!define MAIN_ENTITY #E2EFDA
!define MAIN_ENTITY_2 #FCE4D6

!define METAL #F2F2F2
!define MASTER_MARK_COLOR
!define TRANSACTION_MARK_COLOR FFAA00

skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
}

package "ライセンス管理システム" as target_system {

    entity "Board" as Board <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + ライセンス管理ID [PK]
        --
        名前 / name
        説明 / description
    }

    entity "Topic" as Topic <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + ライセンス発行ID   [PK]
        --
        # BoardID / BoardID [FK]
        # 作成者 / starter [FK]
        --
        メッセージ / subject
        前回更新日 / last_updated
        表示回数 / views
    }

    entity "Post" as Post <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + PostID   [PK]
        --
        # TopicID / TopicID [FK]
        # 作成者 / created_by [FK]
        # 更新者 / updated_by [FK]
        --
        メッセージ / message
        記事 / created_date
        作成日 / created_at
        更新日 / updated_at
    }

    entity "User" as User <<T,TRANSACTION_MARK_COLOR>> MAIN_ENTITY_2 {
        + メッセージ履歴ID [PK]
        --
        ユーザー名/created_date
        パスワード/created_date
        メール/created_date
        スーパーユーザー/created_date
    }
}


Board         ||--|{ Topic
Topic         ||-|{ Post
Topic         ||--|{ User
Post          ||--|{ User



'note right of License : 別プロジェクト\nDB-Linkで参照する

@enduml