# Generated by Django 2.2.5 on 2019-09-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_auto_20190915_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakeibo',
            name='license',
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
